"""empty message

Revision ID: 2cc0ee8498d2
Revises: e726b5a06fdf
Create Date: 2025-10-21 13:31:35.058213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc0ee8498d2'
down_revision = 'e726b5a06fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.drop_column('device')

    # ### end Alembic commands ###
