"""Aumentar tamaño columna device a 255

Revision ID: 87b94bc1f159
Revises: 2cc0ee8498d2
Create Date: 2025-12-26 10:44:44.888790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87b94bc1f159'
down_revision = '2cc0ee8498d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.alter_column('device',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.alter_column('device',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
